[pytest]

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers=
    users: Маркер для тестов связанных с пользователем
    regression: Маркер для регрессионных тестов